# workflow for building and publishing documentation
name: build and publish doc

on:
  push:
    branches:
      - publish
      - docs
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  qgis-job:
    runs-on: ubuntu-latest
    container: qgis/qgis:latest

    steps:
    - name: Inspect container
      run: |
        qgis --version
        python3 -V
        echo $SHELL

    - uses: actions/checkout@v4
      with:
        sparse-checkout: |
          src
          tests

    - name: Install dependencies
      run: |
        python3 -m venv --system-site-package .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip wheel setuptools setuptools_scm
        pip install -r requirements.doc.txt
      shell: bash

    - name: Build package
      run: |
        ls
        source .venv/bin/activate
        mkdir -p doc
        pdoc --html --force --output-dir doc --filter=src,tests --config latex_math=True .
        ls doc
      shell: bash

     - uses: actions/upload-pages-artifact@v3
       with:
         path: 'doc/fire2a-lib'

  deploy-job:
    needs: qgis-job
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
