name: dev publishing on GitHub Releases

on:
  push:
    branches:
      - dev
  workflow_dispatch:

permissions:
  contents: write

jobs:
  qgis-job:
    runs-on: ubuntu-latest
    container: qgis/qgis:latest

    steps:
    - name: Inspect container
      run: |
        qgis --version
        python3 -V
        echo $SHELL

    - uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Install dependencies
      run: |
        python3 -m venv .venv --system-site-packages
        source .venv/bin/activate
        python -m pip install --upgrade pip wheel setuptools setuptools_scm
        pip install build
        pip install -r requirements.txt
      shell: bash

    - name: Build package
      run: |
        source .venv/bin/activate
        python -m build
      shell: bash

    - name: Create Release
      id: create_release
      uses: actions/create-release@v1
      with:
        tag_name: ${{ github.sha }}
        release_name: "Release ${{ github.sha }}"
        draft: true
        prerelease: true
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Upload Release Assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./dist/*.whl
        asset_name: $(basename ./dist/*.whl)
        asset_content_type: application/zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
