name: publishing on pypi

on: 
  push:
    branches:
      - publish
    tags:
      - 'v*'
  workflow_dispatch:

jobs:
  qgis-job:
    runs-on: ubuntu-latest
    container: qgis/qgis:latest

    steps:
    - name: Inspect container
      run: |
        qgis --version
        python3 -V
        echo $SHELL

    - uses: actions/checkout@v3
      with:
        fetch-depth: 0

          # - name: Set up Python
          #   uses: actions/setup-python@v4
          #   with:
          #     python-version: '3.9'

    - name: Install dependencies
      run: |
        python3 -m venv .venv --system-site-packages
        source .venv/bin/activate
        python -m pip install --upgrade pip wheel setuptools
        pip install build twine
        pip install -r requirements.txt
      shell: bash


    - name: Build package
      run: |
        source .venv/bin/activate
        python -m build
      shell: bash

    - name: Publish package to PyPI
      if: startsWith(github.ref, 'refs/tags/v')
      run: |
        source .venv/bin/activate
        twine upload dist/*
      env:
        TWINE_USERNAME: ${{ secrets.PYPI_USERNAME }}
        TWINE_PASSWORD: ${{ secrets.PYPI_PASSWORD }}
      shell: bash
